spring:
  application:
    name: boot3

management:
  endpoints:
    web:
      exposure:
        include: '*'


#server:
#  tomcat:
#    max-connections: 10000  # ?? ?? ?, ???? 10000
#    connection-timeout: 20000  # ?? ????(???), ???? 20000 (20?)
#    threads:
#      max: 200  # ?? ??? ?, ???? 200
#      min-spare: 10  # ?? ????? ?? ?? ??? ?, ???? 10