management:

    endpoints:
        web:
            exposure:
                include:
                    - "*"
                    - "health"
                    - "metrics"
                    - "prometheus"
    endpoint:
        health:
            probes:
                enabled: true
            show-details: always