### GET request with a header
GET http://localhost:8888/licensingservice/default
Accept: application/json

### GET request with a header
GET http://localhost:8888/licensingservice/dev
Accept: application/json

###
POST http://localhost:8888/encrypt
Accept: text/plain

legendaiwjgnz;6icnzl1

###