openapi: 3.0.1
info:
  title: member-api
  description: My API description
  version: master-2.7.14
servers:
- url: http://localhost:2222
  description: Sandbox server
tags:
- name: EXTERNAL
  description: 외부 공개 API
- name: INTERNAL
  description: 내부 API
paths:
  /api/members:
    get:
      tags:
      - EXTERNAL
      summary: Member 페이지 조회
      description: |-
        * 블라블라
        * 블라
      operationId: member-api-test/member_page_test
      parameters:
      - name: size
        in: query
        description: size
        required: false
        schema:
          type: string
      - name: page
        in: query
        description: page
        required: false
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageResponse<MemberResponse>'
              examples:
                member-api-test/member_page_test:
                  value: |-
                    {
                      "total_elements" : 5,
                      "total_pages" : 5,
                      "size" : 1,
                      "number" : 0,
                      "number_of_elements" : 1,
                      "last" : false,
                      "first" : true,
                      "empty" : false,
                      "content" : [ {
                        "id" : 5,
                        "email" : "zoo@bbb.com",
                        "name" : "zoo",
                        "status" : "NORMAL",
                        "address" : null
                      } ]
                    }
    post:
      tags:
      - INTERNAL
      summary: Member 생성
      description: |-
        * 블라블라
        * 블라
      operationId: member-api-test/member_create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MemberSignUpRequest'
            examples:
              member-api-test/member_create:
                value: |-
                  {
                    "email" : "zoo@bbb.com",
                    "name" : "zoo",
                    "status" : "NORMAL"
                  }
              member-api-test/member_create_글자_length_실패:
                value: |-
                  {
                    "email" : "asd",
                    "name" : "asd",
                    "status" : "NORMAL"
                  }
      responses:
        "200":
          description: "200"
        "400":
          description: "400"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                member-api-test/member_create_글자_length_실패:
                  value: |-
                    {
                      "message" : " Invalid Input Value",
                      "status" : 400,
                      "code" : "C001",
                      "errors" : [ {
                        "field" : "email",
                        "value" : "asd",
                        "reason" : "must be a well-formed email address"
                      } ],
                      "timestamp" : "2023-11-23T01:32:24.670011"
                    }
  /api/members/{id}:
    get:
      tags:
      - INTERNAL
      - EXTERNAL
      summary: Member 조회 - 잘못된 요청
      description: 잘못된 ID 또는 필요한 정보가 누락된 경우에 대한 응답 예시.
      operationId: member-api-test/member_get
      parameters:
      - name: id
        in: path
        description: ""
        required: true
        schema:
          type: string
      responses:
        "400":
          description: "400"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                member-api-test/member_get_bad_request:
                  value: |-
                    {
                      "message" : " Invalid Input Value",
                      "status" : 400,
                      "code" : "C001",
                      "errors" : [ ],
                      "timestamp" : "2023-11-23T01:32:24.815231"
                    }
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MemberResponse'
              examples:
                member-api-test/member_get:
                  value: |-
                    {
                      "id" : 1,
                      "email" : "yun@bbb.com",
                      "name" : "yun",
                      "status" : "BAN",
                      "address" : null
                    }
components:
  schemas:
    PageResponse<MemberResponse>:
      title: PageResponse<MemberResponse>
      required:
      - content
      - empty
      - first
      - last
      - number
      - number_of_elements
      - size
      - total_elements
      - total_pages
      type: object
      properties:
        number:
          type: number
          description: number
        last:
          type: boolean
          description: last
        size:
          type: number
          description: size
        total_elements:
          type: number
          description: total_elements
        total_pages:
          type: number
          description: total_pages
        number_of_elements:
          type: number
          description: number_of_elements
        content:
          type: array
          description: content
          items:
            required:
            - email
            - id
            - name
            - status
            type: object
            properties:
              address:
                type: string
                description: address
              name:
                maxLength: 50
                minLength: 1
                type: string
                description: asd
              id:
                type: number
                description: ID
              email:
                maxLength: 50
                minLength: 1
                type: string
                description: email
              status:
                type: string
                description: status
                enum:
                - LOCK
                - NORMAL
                - BAN
        first:
          type: boolean
          description: first
        empty:
          type: boolean
          description: empty
    ErrorResponse:
      title: ErrorResponse
      required:
      - code
      - errors
      - message
      - status
      - timestamp
      type: object
      properties:
        code:
          minLength: 1
          type: string
          description: Error Code
        message:
          minLength: 1
          type: string
          description: Error Message
        errors:
          type: array
          description: Error Array
          items:
            required:
            - field
            - reason
            - value
            type: object
            properties:
              reason:
                minLength: 1
                type: string
                description: Error reason
              field:
                minLength: 1
                type: string
                description: Error field
              value:
                minLength: 1
                type: string
                description: Error value
        timestamp:
          minLength: 1
          type: string
          description: Error Timestamp
        status:
          type: number
          description: HTTP Status Code
    MemberResponse:
      title: MemberResponse
      required:
      - email
      - id
      - name
      - status
      type: object
      properties:
        address:
          type: string
          description: address
        name:
          maxLength: 50
          minLength: 1
          type: string
          description: asd
        id:
          type: number
          description: ID
        email:
          maxLength: 50
          minLength: 1
          type: string
          description: email
        status:
          type: string
          description: status
          enum:
          - LOCK
          - NORMAL
          - BAN
    MemberSignUpRequest:
      title: MemberSignUpRequest
      required:
      - email
      - name
      - status
      type: object
      properties:
        name:
          maxLength: 50
          minLength: 1
          type: string
          description: asd
        email:
          maxLength: 50
          minLength: 1
          type: string
          description: email
        status:
          type: string
          description: status
          enum:
          - LOCK
          - NORMAL
          - BAN
