GET http://localhost:8080/licenses?page=0&size=2
Content-Type: application/json

###

GET http://localhost:8080/licenses/property
Accept: application/json

###

POST http://localhost:8080/actuator/refresh
Accept: application/json

###


# Eureka
GET {{eureka-server}}/eureka/apps/organization-service
Accept: application/json

###