GET {{licensing-service}}/licenses?page=0&size=2
Content-Type: application/json

###

GET {{licensing-service}}/licenses/property
Accept: application/json

###

POST {{licensing-service}}/actuator/refresh
Accept: application/json

###