GET {{zuul-server}}/api/licensing/licenses?size=10&page=10&sleep=3500
Accept: application/json

###

GET {{zuul-server}}/api/organization/organizations/1
Accept: application/json

###

GET {{zuul-server}}/actuator
Accept: application/json

###

GET {{zuul-server}}/actuator/routes
Accept: application/json

###

POST {{zuul-server}}/actuator/refresh
Accept: application/json

###