# licenses

GET {{zuul-server}}/api/licensing/licenses?size=10&page=10&sleep=1
Accept: application/json

###

GET {{zuul-server}}/api/licensing/licenses/organizations/1
Accept: application/json

###

GET {{zuul-server}}/api/licensing/licenses/property
Accept: application/json

###

POST {{zuul-server}}/api/licensing/actuator/bus-refresh
Accept: application/json

###

# organization

GET {{zuul-server}}/api/organization/organizations/1
Accept: application/json

###

GET {{zuul-server}}/actuator
Accept: application/json

###

GET {{zuul-server}}/actuator/routes
Accept: application/json

###

POST {{zuul-server}}/actuator/refresh
Accept: application/json

###