POST http://localhost:8080/a-service
Content-Type: application/json

{
  "name": "asd",
  "email": "aasd@asd.com"
}

###


POST http://localhost:8080/a-service
Content-Type: application/json

{
  "name": "",
  "email": "asd"
}

###