GET {{host}}/hello
Content-Type: application/json

###


GET {{host}}/setFruit?name=banana
Content-Type: application/json

###

GET {{host}}/getFruit?name=apple
Content-Type: application/json

###


GET {{host}}/login?name=yun
Content-Type: application/json

###

GET {{host}}/myName
Content-Type: application/json

###


GET {{host}}/users/1/profile
Content-Type: application/json

###


GET {{host}}/setScore?userId=c&score=55
Content-Type: application/json

###


GET {{host}}/getRank?userId=yun
Content-Type: application/json

###


GET {{host}}/getTopRanks
Content-Type: application/json

###