###

GET {{host}}{{v1}}/members?
    page=0&
    size=10&
    email=member3
Content-Type: application/json

###


###

GET {{host}}{{v1}}/members/name?
    name=member37@example.com
Content-Type: application/json

###

