###

GET {{host}}{{v1}}/members?
    page=0&
    size=10&
    email=member3
Content-Type: application/json

###


###

GET {{host}}{{v1}}/members/name?
    name=address detail 38
Content-Type: application/json

###


GET {{host}}{{v1}}/members/test
Content-Type: application/json

###


GET {{host}}{{v1}}/members/update?
    count=500&
    name=aaaaaawwwdd
Content-Type: application/json

###


GET {{host}}{{v1}}/members/update/bulk?
    count=10000&
    name=asdasdasdasdasd
Content-Type: application/json

###


GET {{host}}{{v1}}/members/update/updateFirst?
    count=200&
    name=asdasdasdasdasd
Content-Type: application/json

###