###

GET {{host}}{{v1}}/members?
    page=0&
    size=10&
    email=member3
Content-Type: application/json

###


###

GET {{host}}{{v1}}/members/name?
    name=Member 33
Content-Type: application/json

###

