#
GET http://localhost:8080/posts?page=1000&size=100

###

#
GET http://localhost:8080/posts/lookup?limit=1

###

#
GET http://localhost:8080/posts/post-with-author?limit=1000

###


#
GET http://localhost:8080/posts/post-only?limit=1000

###

#
GET http://localhost:8080/posts/post-only-one


###

#
GET http://localhost:8080/posts/post-with-author-one

###




#
GET http://localhost:8080/posts/find-lazy-true

###

#
GET http://localhost:8080/posts/find-lazy-false

###

#
GET http://localhost:8080/posts/find

###


###

GET http://localhost:8080/posts/insert?limit=4000


#asdasdaasd
#asdasd
#asdsa