# curl -X GET --location "http://localhost:8080/actuator/health"
#-H "Accept: application/json"
GET http://localhost:8080/actuator/health
Accept: application/json

###



# health
GET {{shop-service}}/actuator/health
Accept: application/json

###


# Shop 조회
GET {{shop-service}}/api/v1/shop?page=1&size=10&name=test&email=test@ad.com&address=xxxxx&zipCode=xxxxxx
Accept: application/json

###

# Shopt 등록
POST {{shop-service}}/api/v1/shop
Content-Type: application/json

{
  "brn": "brn$-{it}",
  "name": "name$-{it}",
  "band": "band$-{it}",
  "category": "category$-{it}",
  "email": "email$-{it}",
  "website": "website$-{it}",
  "openingHours": "openingHours$-{it}",
  "seatingCapacity": 1,
  "rating": 1,
  "address": "address$-{it}",
  "addressDetail": "addressDetail$-{it}",
  "zipCode": "zipCode$-{it}"
}


###


# 자동완성
GET {{shop-service}}/api/
Accept: application/json

###



# 자동완성
GET {{shop-service}}/api/
Accept: application/json

###


