# Config Server
GET {{config-server}}/licensing-service/default
Accept: application/json

###
GET {{config-server}}/licensing-service/dev
Accept: application/json

###
POST {{config-server}}/encrypt
Accept: text/plain

legendaiwjgnz;6icnzl1

###

GET {{config-server}}/licensing-service/default?page=10&size=10&name=123&email=123@asd.com
Accept: application/json

###
