management:
    endpoints:
        web:
            exposure:
                include:
                    - "*"
                    - "health"
                    - "metrics"
                    - "prometheus"