GET {{server}}/books/book/_search?q=hamlet&pretty

###

GET {{server}}books/_search?q=hamlet&pretty

###




GET http://124.80.103.104:9200/books,magazines/_search?q=time&pretty

###

GET http://124.80.103.104:9200/_all/_search?q=time&pretty

###

GET http://124.80.103.104:9200/_search?q=title:time&pretty

###

###

GET http://124.80.103.104:9200/_search?q=title:time%20AND%20machine&pretty

###


###

GET http://124.80.103.104:9200/_search?q=time&df=title&pretty

###



###

GET http://124.80.103.104:9200/_search?q=title:time%20machine&default_operator=AND&pretty

###

###

###

GET http://124.80.103.104:9200/_search?q=title:time&explain&pretty

###

GET http://124.80.103.104:9200/_search?q=title:time&_source=false&pretty

###

GET http://124.80.103.104:9200/_search?q=title:time&fields=title,author,category&pretty

###

GET http://124.80.103.104:9200/_search?q=title:time&_source=title,author,category&pretty

###


GET http://124.80.103.104:9200/books/_search?q=author:jules&sort=pages&pretty

###


GET http://124.80.103.104:9200/books/_search?q=author:jules&sort=pages:desc&pretty

###

GET http://124.80.103.104:9200/books/_search?q=author:jules&_source=title&from=1&pretty

###



GET http://124.80.103.104:9200/books/_search?size=1&q=author:William&search_type=query_then_fetch&_source=title,author&pretty

###

GET http://124.80.103.104:9200/books/_search?size=1&q=author:William&search_type=query_and_fetch&_source=title,author&pretty

###

GET http://124.80.103.104:9200/books/_search?size=1&q=author:William&search_type=query_and_fetch&_source=title,author&pretty

###




GET http://124.80.103.104:9200/books/_search?q=author:william&_source=title,author&search_type=dfs_query_and_fetch&pretty

###












###



###


POST http://124.80.103.104:9200/books/_search?pretty
Content-Type: application/json

{
  "query": {
    "term": {
      "author": "william"
    }
  }
}

###

POST http://124.80.103.104:9200/books/_search?pretty
Content-Type: application/json

{
  "from": 1,
  "size": 2,
  "_source": [
    "title",
    "category"
  ],
  "query": {
    "term": {
      "_all": "time"
    }
  }
}

###

# curl 'http://124.80.103.104:9200/_search?pretty' -d '
#{
#  from : 1,
#  size : 2,
#  fields : ["title","category"],
#  "query" : {
#    "term" : { "_all" : "time" }
#  }
#}'
POST http://124.80.103.104:9200/_search?pretty
Content-Type: application/json


{
  "from": 1,
  "size": 2,
  "_source": [
    "title",
    "category"
  ],
  "query": {
    "term": {
      "_all": "time"
    }
  }
}

###


###


POST http://124.80.103.104:9200/books/_search?pretty
Content-Type: application/json

{
  "_source": [
    "title",
    "author",
    "category",
    "pages"
  ],
  "sort": [
    {
      "category": "desc"
    },
    "pages",
    "title"
  ],
  "query": {
    "term": {
      "_all": "time"
    }
  }
}

###



###


POST http://124.80.103.104:9200/books/_search?pretty
Content-Type: application/json


{
  "_source": [
    "title",
    "author",
    "category",
    "pages"
  ],
  "sort": [
    {
      "category": {
        "order": "desc",
        "mode": "min"
      }
    },
    "pages",
    "title"
  ],
  "query": {
    "term": {
      "category": "science"
    }
  }
}

###



PUT http://192.168.0.10:9200/hotels
Content-Type: application/json

{
  "mappings" : {
    "hotel" : {
      "properties" : {
        "name" : { "type" : "string" },
        "stars" : { "type" : "long" },
        "rooms" : { "type" : "long" },
        "location" : { "type" : "geo_point" },
        "city" : { "type" : "string" },
        "address" : { "type" : "string" },
        "internet" : { "type" : "boolean" },
        "service" : { "type" : "string", "index" : "not_analyzed" },
        "checkin": { "type" : "date" , "format" : "dateOptionalTime"}
      }
    }
  }
}

###

PUT http://192.168.0.10:9200/hotels
Content-Type: application/json

{
  "mappings" : {
    "properties" : {
      "name" : { "type" : "text" },
      "stars" : { "type" : "long" },
      "rooms" : { "type" : "long" },
      "location" : { "type" : "geo_point" },
      "city" : { "type" : "text" },
      "address" : { "type" : "text" },
      "internet" : { "type" : "boolean" },
      "service" : { "type" : "keyword" },
      "checkin": { "type" : "date" , "format" : "dateOptionalTime"}
    }

  }
}

###


GET http://192.168.0.10:9200

###

# curl -XPOST localhost:9200/_bulk --data-binary @6_1_hotels.json
POST http://192.168.0.10:9200/_bulk
Content-Type: application/x-www-form-urlencoded

< 6_1_hotels.json

###
POST http://192.168.0.10:9200/_bulk
Content-Type: application/json

< 6_1_hotels.json

###


# curl 'localhost:9200/hotels/_search?pretty' -d '
#{
#  "aggs" : {
#    "price_min" : {
#      "min" : { "field" : "price" }
#    }
#  }
#}'
POST localhost:9200/hotels/_search?pretty
Content-Type: application/json

{
  "aggs" : {
    "price_min" : {
      "min" : { "field" : "price" }
    }
  }
}

###

