version: "3"
services:
    my-redis-a:
        hostname: redis-master
        container_name: redis-master
        image: "bitnami/redis"
        environment:
            - REDIS_REPLICATION_MODE=master
            - ALLOW_EMPTY_PASSWORD=yes
        ports:
            - 5000:6379
    my-redis-b:
        hostname: redis-replicas-1
        container_name: redis-replicas-1
        image: "bitnami/redis"
        environment:
            - REDIS_REPLICATION_MODE=slave
            - REDIS_MASTER_HOST=redis-master
            - ALLOW_EMPTY_PASSWORD=yes
        ports:
            - 5001:6379
        depends_on:
            - my-redis-a