server:
    port: 0
spring:
    application:
        name: user-service

    cloud:
        bus:
            trace:
                enabled: true
            enabled: true
            refresh:
                enabled: true
            ack:
                enabled: true

    kafka:
        bootstrap-servers: 192.168.0.10:9092

    config:
        import: "optional:configserver:http://localhost:8888"

eureka:
    instance:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            default-zone: http://localhost:8761/eureka/

feign:
    metrics:
        enabled: true

resilience4j.circuitbreaker:
    configs:
        default:
            failureRateThreshold: 50
            slowCallRateThreshold: 100
            slowCallDurationThreshold: 60000
            permittedNumberOfCallsInHalfOpenState: 4
            maxWaitDurationInHalfOpenState: 1000
            slidingWindowType: COUNT_BASED
            slidingWindowSize: 10
            minimumNumberOfCalls: 10
            waitDurationInOpenState: 10000
    instances:
        findWithOrder:
            baseConfig: default

        metrics:
            enabled: true
            legacy:
                enabled: true
getting:
    message: "Welcome to Simple E-Commerce"

logging:
    level:
        ROOT: info
        com.service.member.client: DEBUG

management:
    endpoints:
        web:
            exposure:
                include:
                    - "*"
#                    - "env"
#                    - "refresh"
#                    - "bus-refresh"
#                    - "bus-env"
#                    - "health"
#                    - "trace"
#                    - "prometheus"
#                    - "metrics"
    endpoint:
        metrics:
            enabled: true
        refresh:
            enabled: true