###
GET http://localhost:8080/customer/1
Accept: application/json

###

GET http://localhost:8080/customer
Accept: application/json

###

POST http://localhost:8080/customer
Content-Type: application/json

{
  "id": 18,
  "name": "new name",
  "telephone": {
    "countryCode": "+02",
    "telephoneNumber": "020232232"
  }
}

###

GET http://localhost:8080/functional/customer/5
Content-Type: application/json

###

GET http://localhost:8080/functional/customers?nameFilter=
Content-Type: application/json

###

POST http://localhost:8080/functional/customer/22
Content-Type: application/json

{
  "name": "Microservice",
  "telephone": {
    "countryCode": "+82",
    "telephoneNumber": "01029333211111"
  }
}

###

POST http://localhost:8080/functional/customer/1
Content-Type: application/jsonk

{
  "name": "Microservice",
  "telephone": {
    "countryCode": "+82",
    "telephoneNumber": "01029333211111"
  }
}
