GET {{order-service}}/orders/profile
Accept: application/json

###

GET {{order-service}}/actuator

###

POST {{order-service}}/actuator/refresh

###

POST {{order-service}}/actuator/bus-refresh

###

POST {{order-service}}/actuator/bus-env

###


GET {{config-server}}/actuator/env
Accept: application/json