GET {{order-service}}/orders/profile
Accept: application/json

###

GET {{order-service}}/actuator

###

POST {{order-service}}/actuator/refresh

###

POST {{order-service}}/actuator/busrefresh

###

POST {{order-service}}/actuator/busenv

###


GET {{config-server}}/actuator/env
Accept: application/json

###


GET {{config-server}}/order-service/local
Accept: application/json