GET {{order-service}}/orders/profile
Accept: application/json

###

GET {{order-service}}/actuator

###

POST {{order-service}}/actuator/refresh

###

POST {{order-service}}/actuator/busrefresh

###




GET {{config-server}}/actuator
Accept: application/json

###

POST {{order-service}}/actuator/busrefresh

###


GET http://localhost:8181/orders/profile
Accept: application/json

###

GET http://localhost:8585/orders/profile
Accept: application/json


###

GET http://localhost:8181/actuator

###

GET http://localhost:8181/trace

###

POST http://localhost:8181/actuator/busenv
Content-Type: application/vnd.spring-boot.actuator.v3+json