GET {{gateway-server}}/order-service/api/v1/orders
Accept: application/json

###

GET {{gateway-server}}/order/orders/carts/1
Accept: application/json

###

GET {{gateway-server}}/order/orders/carts/1/123
Accept: application/json

###

GET {{gateway-server}}/cart/carts?page=0&size=5
Accept: application/json

###

GET {{order-service}}/orders?page=0&size=5
Accept: application/json

###

GET {{cart-service}}/carts

###


GET http://localhost:5555/a-service/a-service
Content-Type: application/json