
POST {{gateway-server}}/user-service/api/v1/users
Content-Type: application/json

{
  "email": "1dasdasd@asd.com",
  "name": "123123",
  "password": "123123"
}

###


GET {{gateway-server}}/user-service/api/v1/users
Content-Type: application/json