GET {{gateway-server}}/user-service/api/v1/users/997a5a8b-80e4-4a5d-b5d1-14ee22be18da/orders?faultPercentage=100&delay=0
Content-Type: application/json

###


GET {{gateway-server}}/user-service/api/v1/users/997a5a8b-80e4-4a5d-b5d1-14ee22be18da/orders?faultPercentage=0&delay=0
Content-Type: application/json


###

POST {{gateway-server}}/user-service/api/v1/users
Content-Type: application/json

{
  "email": "asd@asd.com",
  "name": "asd",
  "password": "asdasd"
}


###
GET {{gateway-server}}/order-service/actuator/health
Content-Type: application/json

###
GET {{gateway-server}}/order-service/actuator/circuitbreakers
Content-Type: application/json

###
GET {{gateway-server}}/order-service/actuator/circuitbreakerevents
Content-Type: application/json

###
GET {{gateway-server}}/order-service/actuator/
Content-Type: application/json

###
GET {{gateway-server}}/order-service/actuator/circuitbreakers/findWithOrder
Content-Type: application/json


###
GET {{gateway-server}}/user-service/actuator/health
Content-Type: application/json

###

GET {{gateway-server}}/user-service/actuator/
Content-Type: application/json


###
GET {{gateway-server}}/user-service/actuator/circuitbreakers
Content-Type: application/json


###
GET {{gateway-server}}/user-service/actuator/circuitbreakerevents
Content-Type: application/json

###
GET {{gateway-server}}/user-service/actuator/circuitbreakers/findWithOrder
Content-Type: application/json


