spring:
    main:
        web-application-type: none

    cache:
        type: redis
    session:
        store-type: redis
    redis:
        host: 127.0.0.1
        port: 6379
        password: root


logging:
    level:
        root: INFO
        redis.clients: TRACE
        org.springframework.data: TRACE